import { AtomIcon, AwardIcon, BadgeCheckIcon, BookCheckIcon, BookIcon, BookOpenCheckIcon, BookOpenIcon, BookTextIcon, BrainIcon, CalculatorIcon, ClipboardIcon, FlaskConicalIcon, GraduationCapIcon, LightbulbIcon, LucideIconData, MedalIcon, MicroscopeIcon, NotebookIcon, NotebookPen, NotebookPenIcon, NotebookTextIcon, PencilIcon, PencilLine, PencilLineIcon, PencilRulerIcon, RulerIcon, SchoolIcon, UniversityIcon } from "lucide-angular";

export type IconMapper = Record<string, LucideIconData>;

export const academicIcons: IconMapper = {
  school: SchoolIcon,
  university: UniversityIcon,
  "graduation-cap": GraduationCapIcon,
  book: BookIcon,
  "book-open": BookOpenIcon,
  "book-open-check": BookOpenCheckIcon,
  "book-check": BookCheckIcon,
  "book-text": BookTextIcon,
  notebook: NotebookIcon,
  "notebook-pen": NotebookPenIcon,
  "notebook-text": NotebookTextIcon,
  pencil: PencilIcon,
  "pencil-line": PencilLineIcon,
  "pencil-ruler": PencilRulerIcon,
  ruler: RulerIcon,
  calculator: CalculatorIcon,
  atom: AtomIcon,
  "flask-conical": FlaskConicalIcon,
  microscope: MicroscopeIcon,
  brain: BrainIcon,
  lightbulb: LightbulbIcon,
  award: AwardIcon,
  medal: MedalIcon,
  "badge-check": BadgeCheckIcon,
  clipboard: ClipboardIcon,
//   "clipboard-list": {},
//   "clipboard-check": {},
//   "file-text": {},
//   "file-check": {},
//   "file-badge": {},
//   presentation: {},
//   "presentation-chart": {},
//   "chart-bar": {},
//   "chart-line": {},
//   calendar: {},
//   "calendar-days": {},
//   "calendar-check": {},
//   "calendar-clock": {},
//   timer: {},
//   clock: {},
//   "alarm-clock": {}
};